name: teman_resto
description: PJBL aplikasi reservasi restoran

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.0
  google_sign_in: ^6.2.1

  # Image Picker
  image_picker: ^1.1.2

  # Session & Storage
  shared_preferences: ^2.2.0

  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
