// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _env(String key) => dotenv.env[key] ?? '';

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _env('FIREBASE_WEB_API_KEY'),
        appId: '1:749004572344:web:5f2ebc7ebbc0f5b47c564d',
        messagingSenderId: '749004572344',
        projectId: 'teman-resto',
        authDomain: 'teman-resto.firebaseapp.com',
        storageBucket: 'teman-resto.firebasestorage.app',
        measurementId: 'G-K4ZSL88S74',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _env('FIREBASE_ANDROID_API_KEY'),
        appId: '1:749004572344:android:630ad1759844a7c97c564d',
        messagingSenderId: '749004572344',
        projectId: 'teman-resto',
        storageBucket: 'teman-resto.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _env('FIREBASE_IOS_API_KEY'),
        appId: '1:749004572344:ios:ff353432deacc00b7c564d',
        messagingSenderId: '749004572344',
        projectId: 'teman-resto',
        storageBucket: 'teman-resto.firebasestorage.app',
        iosBundleId: 'com.example.temanRestoPjbl',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: _env('FIREBASE_MACOS_API_KEY'),
        appId: '1:749004572344:ios:ff353432deacc00b7c564d',
        messagingSenderId: '749004572344',
        projectId: 'teman-resto',
        storageBucket: 'teman-resto.firebasestorage.app',
        iosBundleId: 'com.example.temanRestoPjbl',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: _env('FIREBASE_WINDOWS_API_KEY'),
        appId: '1:749004572344:web:ab87bd036958b8e97c564d',
        messagingSenderId: '749004572344',
        projectId: 'teman-resto',
        authDomain: 'teman-resto.firebaseapp.com',
        storageBucket: 'teman-resto.firebasestorage.app',
        measurementId: 'G-ZBCSP9BMMV',
      );
}
