// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnodVsitSe8H9ubw0ra4EWMXD_CKg0f_A',
    appId: '1:749004572344:web:5f2ebc7ebbc0f5b47c564d',
    messagingSenderId: '749004572344',
    projectId: 'teman-resto',
    authDomain: 'teman-resto.firebaseapp.com',
    storageBucket: 'teman-resto.firebasestorage.app',
    measurementId: 'G-K4ZSL88S74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYHQ8oAqYZVK284ALfO6tTNkQB9T60ZV0',
    appId: '1:749004572344:android:630ad1759844a7c97c564d',
    messagingSenderId: '749004572344',
    projectId: 'teman-resto',
    storageBucket: 'teman-resto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcsuXbbgIF-LEZa1qUOG8fjZUWFlRX-co',
    appId: '1:749004572344:ios:ff353432deacc00b7c564d',
    messagingSenderId: '749004572344',
    projectId: 'teman-resto',
    storageBucket: 'teman-resto.firebasestorage.app',
    iosBundleId: 'com.example.temanRestoPjbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcsuXbbgIF-LEZa1qUOG8fjZUWFlRX-co',
    appId: '1:749004572344:ios:ff353432deacc00b7c564d',
    messagingSenderId: '749004572344',
    projectId: 'teman-resto',
    storageBucket: 'teman-resto.firebasestorage.app',
    iosBundleId: 'com.example.temanRestoPjbl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnodVsitSe8H9ubw0ra4EWMXD_CKg0f_A',
    appId: '1:749004572344:web:ab87bd036958b8e97c564d',
    messagingSenderId: '749004572344',
    projectId: 'teman-resto',
    authDomain: 'teman-resto.firebaseapp.com',
    storageBucket: 'teman-resto.firebasestorage.app',
    measurementId: 'G-ZBCSP9BMMV',
  );
}
